"""
Single phrase → canonical symptom (dataset column) map for API + CatBoost model.

Keys are the raw symptom column names from the CatBoost training dataset.
The CatBoost model (winner of saca_model_evaluation) uses these same column names
as its feature names, so matches here feed directly into the ML inference vector.
"""

from __future__ import annotations

# fmt: off
PHRASE_TO_CANONICAL: dict[str, str] = {
    # Chest
    "chest pain": "sharp chest pain",
    "chest hurt": "sharp chest pain",
    "chest hurts": "sharp chest pain",
    "chest is hurting": "sharp chest pain",
    "heart pain": "sharp chest pain",
    "heart hurts": "sharp chest pain",
    "pain in chest": "sharp chest pain",
    "chest is sore": "sharp chest pain",
    "sore chest": "sharp chest pain",
    "chest discomfort": "chest tightness",
    "chest feeling tight": "chest tightness",
    "tight chest": "chest tightness",
    # Vision
    "blurred vision": "diminished vision",
    "blurry vision": "diminished vision",
    "can't see clearly": "diminished vision",
    "vision problems": "diminished vision",
    "seeing double": "double vision",
    # Breathing
    "breathless": "shortness of breath",
    "can't breathe": "shortness of breath",
    "cant breathe": "shortness of breath",
    "cannot breathe": "shortness of breath",
    "not breathing properly": "shortness of breath",
    "hard to breathe": "shortness of breath",
    "difficulty breathing": "shortness of breath",
    "trouble breathing": "shortness of breath",
    "no breath": "shortness of breath",
    "out of breath": "shortness of breath",
    "breath is short": "shortness of breath",
    "shortness of breath": "shortness of breath",
    "breathing bad": "shortness of breath",
    "can't get air": "shortness of breath",
    "cant get air": "shortness of breath",
    # Stomach
    "stomach pain": "sharp abdominal pain",
    "stomach ache": "sharp abdominal pain",
    "stomachache": "sharp abdominal pain",
    "tummy ache": "sharp abdominal pain",
    "tummy hurts": "sharp abdominal pain",
    "tummy is sore": "sharp abdominal pain",
    "belly pain": "sharp abdominal pain",
    "belly hurts": "sharp abdominal pain",
    "sore belly": "sharp abdominal pain",
    "sore tummy": "sharp abdominal pain",
    "pain in stomach": "sharp abdominal pain",
    "pain in belly": "sharp abdominal pain",
    "guts hurting": "sharp abdominal pain",
    "guts sore": "sharp abdominal pain",
    "abdominal pain": "sharp abdominal pain",
    # Nausea / Vomiting
    "feel sick": "nausea",
    "feeling sick": "nausea",
    "throwing up": "vomiting",
    "threw up": "vomiting",
    "puking": "vomiting",
    "vomit": "vomiting",
    "vomiting": "vomiting",
    # Heart rhythm
    "heart racing": "increased heart rate",
    "racing heart": "increased heart rate",
    "fast heartbeat": "increased heart rate",
    "heart pounding": "palpitations",
    "slow heartbeat": "decreased heart rate",
    # Head
    "head pain": "headache",
    "head hurts": "headache",
    "head is sore": "headache",
    "sore head": "headache",
    "my head hurts": "headache",
    "head pounding": "headache",
    "head throbbing": "headache",
    "migraine": "headache",
    "headache": "headache",
    # Throat / Nose
    "runny nose": "nasal congestion",
    "blocked nose": "nasal congestion",
    "stuffy nose": "nasal congestion",
    "throat pain": "sore throat",
    "throat hurts": "sore throat",
    "throat is sore": "sore throat",
    "sore throat": "sore throat",
    "can't swallow": "sore throat",
    "cant swallow": "sore throat",
    "throat is closing": "sore throat",
    # Skin
    "rash": "skin rash",
    "itchy skin": "itching of skin",

    # Fever
    "fever": "fever",
    "high temperature": "fever",
    "feeling hot": "fever",
    "burning up": "fever",
    "really hot": "fever",
    "body is hot": "fever",
    "hot all over": "fever",

    # Cough
    "cough": "cough",
    "coughing": "cough",
    "coughing a lot": "cough",
    "bad cough": "cough",
    "keep coughing": "cough",

    # General — including AE2 English phrasings common in NT Aboriginal communities
    "tired": "fatigue",
    "tired all the time": "fatigue",
    "very tired": "fatigue",
    "so tired": "fatigue",
    "no energy": "fatigue",
    "exhausted": "fatigue",
    "fatigue": "fatigue",
    "weak": "weakness",
    "weakness": "weakness",
    "feeling weak": "weakness",
    "body is weak": "weakness",
    "no strength": "weakness",
    "can't get up": "weakness",
    "cant get up": "weakness",
    "dizzy": "dizziness",
    "dizzy feeling": "dizziness",
    "head is spinning": "dizziness",
    "everything is spinning": "dizziness",
    "lightheaded": "dizziness",
    "dizziness": "dizziness",
    "feel like falling": "dizziness",
    "sweat": "sweating",
    "sweating": "sweating",
    "sweating a lot": "sweating",
    "night sweats": "sweating",
    "shivering": "chills",
    "shaking": "chills",
    "shaking all over": "chills",
    "body shaking": "chills",
    "cold and shaking": "chills",
    "no appetite": "decreased appetite",
    "not eating": "decreased appetite",
    "don't feel like eating": "decreased appetite",
    "loss of appetite": "decreased appetite",
    "not hungry": "decreased appetite",
    "weight loss": "recent weight loss",
    "losing weight": "recent weight loss",
    "swollen": "skin swelling",
    "swelling": "skin swelling",
    "puffed up": "skin swelling",
    "muscle ache": "muscle pain",
    "muscles sore": "muscle pain",
    "body ache": "ache all over",
    "aching all over": "ache all over",
    "everything hurts": "ache all over",
    "whole body hurts": "ache all over",
    "sore all over": "ache all over",
    "loose stool": "diarrhea",
    "runny stomach": "diarrhea",
    "bad stomach": "diarrhea",
    "diarrhea": "diarrhea",
    "burning urination": "painful urination",
    "pain passing urine": "painful urination",
    "cant sleep": "insomnia",
    "can't sleep": "insomnia",
    "nervous": "anxiety and nervousness",
    "anxiety": "anxiety and nervousness",
    "worried all the time": "anxiety and nervousness",
    "depressed": "depression",
    "feeling sad": "depression",
    "feeling down": "depression",
    "seizure": "seizures",
    "fitting": "seizures",
    "fit": "seizures",
    "shaking fit": "seizures",
    "confused": "altered sensorium",
    "confusion": "altered sensorium",
    "not making sense": "altered sensorium",
    "acting strange": "altered sensorium",
    "not himself": "altered sensorium",
    "not herself": "altered sensorium",
    "numb": "loss of sensation",
    "numbness": "loss of sensation",
    "can't feel": "loss of sensation",
    "cant feel": "loss of sensation",
    "loss of sensation": "loss of sensation",
    "tingling": "paresthesia",
    "pins and needles": "paresthesia",
    "paresthesia": "paresthesia",
    "abnormal involuntary movements": "abnormal involuntary movements",
    "twitching": "abnormal involuntary movements",
    # Bleeding
    "bleeding": "bleeding",
    "bleeding bad": "bleeding",
    "lot of blood": "bleeding",
    "too much blood": "bleeding",
    # Skin (extended)
    "itchy rash": "skin rash",
    "skin is itchy": "itching of skin",
}
# fmt: on

SYMPTOM_PHRASES = PHRASE_TO_CANONICAL
