# =============================================================================
# SACA Disease Model - Test Setup
# Run from project root: python test_setup.py
# =============================================================================

import os
import sys

# Always resolve paths relative to THIS script's location (project root)
BASE       = os.path.dirname(os.path.abspath(__file__))
DATA_DIR   = os.path.join(BASE, "data", "raw")
MODELS_DIR = os.path.join(BASE, "models")

PASS = 0
FAIL = 0

def test(name, fn):
    global PASS, FAIL
    try:
        fn()
        print(f"  [PASS] {name}")
        PASS += 1
    except Exception as e:
        print(f"  [FAIL] {name} --> {e}")
        FAIL += 1


# ==========================
# 1. Library Import Tests
# ==========================
print("\n== 1. Library Imports ==")

def test_pandas():
    import pandas as pd
    print(f"         pandas           {pd.__version__}", end=" ")

def test_numpy():
    import numpy as np
    print(f"         numpy            {np.__version__}", end=" ")

def test_sklearn():
    import sklearn
    print(f"         scikit-learn     {sklearn.__version__}", end=" ")

def test_lightgbm():
    import lightgbm as lgb
    print(f"         lightgbm         {lgb.__version__}", end=" ")

def test_catboost():
    import catboost as cb
    print(f"         catboost         {cb.__version__}", end=" ")

def test_imblearn():
    import imblearn
    print(f"         imbalanced-learn {imblearn.__version__}", end=" ")

def test_joblib():
    import joblib
    print(f"         joblib           {joblib.__version__}", end=" ")

test("pandas",           test_pandas)
test("numpy",            test_numpy)
test("scikit-learn",     test_sklearn)
test("lightgbm",         test_lightgbm)
test("catboost",         test_catboost)
test("imbalanced-learn", test_imblearn)
test("joblib",           test_joblib)


# ==========================
# 2. File & Folder Structure Tests
# FIX 1: removed decision_tree.pkl — not trained in file 02
# FIX 2: removed test_results.json — not generated by new pipeline
# FIX 3: added all severity model files
# ==========================
print("\n== 2. Project File Structure ==")

REQUIRED_PATHS = [
    # Dataset
    os.path.join(DATA_DIR,   "saca_final_dataset_self.csv"),
    # Disease models
    os.path.join(MODELS_DIR, "lightgbm_model.pkl"),
    os.path.join(MODELS_DIR, "catboost_model.cbm"),
    os.path.join(MODELS_DIR, "label_encoder.pkl"),
    os.path.join(MODELS_DIR, "disease_feature_columns.pkl"),
    # Severity models
    os.path.join(MODELS_DIR, "lgbm_severity_model.pkl"),
    os.path.join(MODELS_DIR, "catboost_severity_model.pkl"),
    os.path.join(MODELS_DIR, "severity_map.pkl"),
    os.path.join(MODELS_DIR, "severity_feature_columns.pkl"),
]

for path in REQUIRED_PATHS:
    test(f"exists: {os.path.relpath(path, BASE)}", lambda p=path: (
        (_ for _ in ()).throw(FileNotFoundError(f"Not found: {p}"))
        if not os.path.exists(p) else None
    ))


# ==========================
# 3. Dataset Load Test
# ==========================
print("\n== 3. Dataset ==")

def test_dataset_load():
    import pandas as pd
    df = pd.read_csv(os.path.join(DATA_DIR, "saca_final_dataset_self.csv"))
    assert df.shape[0] > 0,          "Dataset is empty"
    assert "diseases" in df.columns, "Missing 'diseases' column"
    assert "Severity" in df.columns, "Missing 'Severity' column"
    print(f"         rows={df.shape[0]:,}  cols={df.shape[1]}  "
          f"diseases={df['diseases'].nunique()}", end=" ")

test("CSV loads correctly", test_dataset_load)


# ==========================
# 4. Disease Model Load Tests
# FIX: removed decision_tree.pkl test — not in pipeline
# ==========================
print("\n== 4. Disease Model Loading ==")

def test_load_lgb():
    import joblib
    model = joblib.load(os.path.join(MODELS_DIR, "lightgbm_model.pkl"))
    assert hasattr(model, "predict"), "LGB has no predict()"

def test_load_cb():
    import catboost as cb
    model = cb.CatBoostClassifier()
    model.load_model(os.path.join(MODELS_DIR, "catboost_model.cbm"))
    assert hasattr(model, "predict"), "CB has no predict()"

def test_load_le():
    import joblib
    le = joblib.load(os.path.join(MODELS_DIR, "label_encoder.pkl"))
    assert hasattr(le, "classes_"), "LabelEncoder missing classes_"
    print(f"         {len(le.classes_)} disease classes loaded", end=" ")

test("Disease LightGBM loads",  test_load_lgb)
test("Disease CatBoost loads",  test_load_cb)
test("Disease LabelEncoder loads", test_load_le)


# ==========================
# 5. Severity Model Load Tests
# FIX: added severity model loading tests
# ==========================
print("\n== 5. Severity Model Loading ==")

def test_load_severity_models():
    import joblib
    lgbm_sev = joblib.load(os.path.join(MODELS_DIR, "lgbm_severity_model.pkl"))
    cat_sev  = joblib.load(os.path.join(MODELS_DIR, "catboost_severity_model.pkl"))
    sev_map  = joblib.load(os.path.join(MODELS_DIR, "severity_map.pkl"))
    assert hasattr(lgbm_sev, "predict"), "LGBM severity has no predict()"
    assert hasattr(cat_sev,  "predict"), "CB severity has no predict()"
    assert isinstance(sev_map, dict),    "severity_map is not a dict"
    print(f"         severity classes: {list(sev_map.keys())}", end=" ")

test("Severity models load", test_load_severity_models)


# ==========================
# 6. Disease Prediction Smoke Test
# ==========================
print("\n== 6. Disease Prediction Smoke Test ==")

def test_disease_prediction():
    import joblib, numpy as np, catboost as cb, re
    import pandas as pd

    le        = joblib.load(os.path.join(MODELS_DIR, "label_encoder.pkl"))
    model_lgb = joblib.load(os.path.join(MODELS_DIR, "lightgbm_model.pkl"))
    model_cb  = cb.CatBoostClassifier()
    model_cb.load_model(os.path.join(MODELS_DIR, "catboost_model.cbm"))

    df = pd.read_csv(os.path.join(DATA_DIR, "saca_final_dataset_self.csv"))

    # Replicate rare class grouping from 02_disease_prediction.py
    y = df["diseases"]
    disease_counts = y.value_counts()
    rare_diseases  = disease_counts[disease_counts < 10].index
    df["diseases"] = y.replace(rare_diseases, "Other_Rare_Disease")

    X = df.drop(["diseases", "Severity"], axis=1)

    def clean_feature_names(columns):
        cleaned = []
        seen = set()
        for col in columns:
            c = re.sub(r"[^A-Za-z0-9_]+", "_", col).strip("_").lower()
            if not c: c = "feature"
            orig, i = c, 1
            while c in seen:
                c = f"{orig}_{i}"; i += 1
            seen.add(c)
            cleaned.append(c)
        return cleaned

    X.columns = clean_feature_names(list(X.columns))
    sample    = X.iloc[[0]]

    lgb_prob = np.asarray(model_lgb.predict(sample))
    lgb_pred = le.inverse_transform([np.argmax(lgb_prob)])[0]
    cb_pred  = le.inverse_transform(model_cb.predict(sample).flatten())[0]

    print(f"         LightGBM → {lgb_pred} | CatBoost → {cb_pred}", end=" ")
    assert isinstance(lgb_pred, str), "LGB prediction not a string"
    assert isinstance(cb_pred,  str), "CB  prediction not a string"

test("Disease models predict correctly", test_disease_prediction)


# ==========================
# 7. Severity Prediction Smoke Test
# FIX: added severity prediction test
# ==========================
print("\n== 7. Severity Prediction Smoke Test ==")

def test_severity_prediction():
    import joblib, numpy as np, re
    import pandas as pd

    lgbm_sev = joblib.load(os.path.join(MODELS_DIR, "lgbm_severity_model.pkl"))
    cat_sev  = joblib.load(os.path.join(MODELS_DIR, "catboost_severity_model.pkl"))
    sev_map  = joblib.load(os.path.join(MODELS_DIR, "severity_map.pkl"))

    # Reverse map for decoding: {0: 'Mild', 1: 'Moderate', 2: 'Severe'}
    inv_sev_map = {v: k for k, v in sev_map.items()}

    df = pd.read_csv(os.path.join(DATA_DIR, "saca_final_dataset_self.csv"))
    X  = df.drop(["diseases", "Severity"], axis=1)

    def clean_feature_names(columns):
        cleaned = []
        seen = set()
        for col in columns:
            c = re.sub(r"[^A-Za-z0-9_]+", "_", col).strip("_").lower()
            if not c: c = "feature"
            orig, i = c, 1
            while c in seen:
                c = f"{orig}_{i}"; i += 1
            seen.add(c)
            cleaned.append(c)
        return cleaned

    X.columns  = clean_feature_names(list(X.columns))
    sample     = X.iloc[[0]]

    lgb_sev_pred = inv_sev_map[lgbm_sev.predict(sample)[0]]
    cat_sev_pred = inv_sev_map[cat_sev.predict(sample).flatten()[0]]

    print(f"         LightGBM → {lgb_sev_pred} | CatBoost → {cat_sev_pred}", end=" ")
    assert lgb_sev_pred in ["Mild", "Moderate", "Severe"], "LGB severity invalid"
    assert cat_sev_pred in ["Mild", "Moderate", "Severe"], "CB  severity invalid"

test("Severity models predict correctly", test_severity_prediction)


# ==========================
# Summary
# ==========================
total = PASS + FAIL
print(f"\n{'='*45}")
print(f"  Results: {PASS}/{total} passed", end="  ")
print(f"{'ALL GOOD! ✓' if FAIL == 0 else f'{FAIL} FAILED ✗'}")
print(f"{'='*45}\n")

sys.exit(0 if FAIL == 0 else 1)